# Generated by Django 4.2.6 on 2023-10-07 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormFactor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Voltage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.IntegerField(choices=[(115, "115V"), (230, "230V")])),
            ],
        ),
        migrations.CreateModel(
            name="Wattage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PSU",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "average_efficiency",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "average_efficiency_5vsb",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("vampire_power", models.DecimalField(decimal_places=7, max_digits=8)),
                ("average_power_factor", models.DecimalField(decimal_places=3, max_digits=4)),
                ("average_noise_output", models.DecimalField(decimal_places=2, max_digits=4)),
                ("date", models.DateField()),
                ("report_short", models.URLField()),
                ("report", models.URLField()),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="common.brand")),
                (
                    "efficiency_rating",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="common.efficiencycertification"),
                ),
                ("form_factor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="psu.formfactor")),
                (
                    "noise_rating",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="common.noisecertification"),
                ),
                ("tags", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="psu.tag")),
                ("voltage", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="psu.voltage")),
                (
                    "wattage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="psu.wattage",
                        validators=[django.core.validators.StepValueValidator(limit_value=50)],
                    ),
                ),
            ],
        ),
    ]
