# Generated by Django 4.2.6 on 2023-10-09 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_alter_efficiencycertification_image_and_more"),
        ("psu", "0002_alter_psu_efficiency_rating_alter_psu_noise_rating_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PSU",
            new_name="PsuEntry",
        ),
    ]
