# Generated by Django 4.2.6 on 2023-10-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psu", "0003_rename_psu_psuentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psuentry",
            name="report",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="psuentry",
            name="report_short",
            field=models.URLField(blank=True),
        ),
    ]
