# Generated by Django 4.2.6 on 2023-10-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("psu", "0004_alter_psuentry_report_alter_psuentry_report_short"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psuentry",
            name="wattage",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="psu.wattage"),
        ),
    ]
