# Generated by Django 4.2.6 on 2023-10-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_alter_efficiencycertification_image_and_more"),
        ("psu", "0005_alter_psuentry_wattage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psuentry",
            name="efficiency_rating",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="common.efficiencycertification"
            ),
        ),
        migrations.AlterField(
            model_name="psuentry",
            name="noise_rating",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="common.noisecertification"
            ),
        ),
        migrations.AlterField(
            model_name="psuentry",
            name="report",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psuentry",
            name="report_short",
            field=models.URLField(blank=True, null=True),
        ),
    ]
