# Generated by Django 4.2.6 on 2023-10-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psu", "0006_alter_psuentry_efficiency_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psuentry",
            name="average_noise_output",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
