# Generated by Django 4.2.6 on 2023-10-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="efficiencycertification",
            name="image",
        ),
        migrations.RemoveField(
            model_name="noisecertification",
            name="image",
        ),
        migrations.AddField(
            model_name="efficiencycertification",
            name="file_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="noisecertification",
            name="file_name",
            field=models.CharField(default="d", max_length=50),
            preserve_default=False,
        ),
    ]
