# Generated by Django 4.2.6 on 2023-10-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_remove_efficiencycertification_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="efficiencycertification",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="noisecertification",
            name="file_name",
        ),
        migrations.AddField(
            model_name="efficiencycertification",
            name="image",
            field=models.ImageField(blank=True, upload_to="efficiency"),
        ),
        migrations.AddField(
            model_name="noisecertification",
            name="image",
            field=models.ImageField(blank=True, upload_to="noise"),
        ),
    ]
