# Generated by Django 4.2.6 on 2023-10-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_remove_efficiencycertification_file_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="efficiencycertification",
            name="image",
            field=models.ImageField(blank=True, upload_to="media/efficiency"),
        ),
        migrations.AlterField(
            model_name="noisecertification",
            name="image",
            field=models.ImageField(blank=True, upload_to="media/noise"),
        ),
    ]
